- hosts: localhost
  become: true
  pre_tasks:
    - include: adding_key.yml
    - include : adding_repos.yml
    - include: update.yml
           

    # install the packages
  tasks:
    - include: tasks/users.yml
    - include: tasks/packages.yml
    - include: tasks/cron.yml