- hosts: localhost
  become: true
  pre_tasks:
    -name: update repos
     apt:update_cache=yes 
     apt:upgrade=yes
        
        
        
     changed_when: false


  tasks:
    -include: tasks/packages.yml	
