- hosts: localhost
  become: true
  pre_tasks:
  
   
  
    - name: add key
      apt_key:  
        url: https://dl-ssl.google.com/linux/linux_signing_key.pub 
        state: present
      
    - name: add repository for chrome
      apt_repository: 
        repo: deb http://dl.google.com/linux/chrome/deb/ stable main
        filename: google
        
     -name: add repository for brackets
        apt_repository:
         repo: ppa:webupd8team/brackets   
      
    - name: update repositories
      apt: update_cache=yes upgrade=yes
      changed_when: False
      


  tasks:
    - include: tasks/packages.yml