- hosts: localhost
  become: true
  pre_tasks:
  
   
  # adding the key for google repository
    - name: add key
      apt_key:  
        url: https://dl-ssl.google.com/linux/linux_signing_key.pub 
        state: present
   # adding the repository for chrome   
    - name: add repository for chrome
      apt_repository: 
        repo: deb http://dl.google.com/linux/chrome/deb/ stable main
        filename: google
    # adding the repository for brackets    
    - name: add repository for brackets
      apt_repository:
        repo: ppa:webupd8team/brackets
        
    # update/upgrade the repositories 
    - name: update repositories
      apt: update_cache=yes upgrade=yes
      changed_when: False
      

    # install the packages
  tasks:
    - include: tasks/packages.yml